### ISSUE TITLE
Add port forwards like kitchen-docker

### ISSUE THREAD

**Issue by joerg** [marcy-terui/kitchen-docker_cli#10]
The kitchen-docker has port forwards which currently is the only reason I am not using docker_cli. Their code for it is here: https://github.com/portertech/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb#L230

**Comment by marcy-terui** [comment]
It is possible with `publish` option.
https://github.com/marcy-terui/kitchen-docker_cli/blob/master/README.md#publish
https://github.com/marcy-terui/kitchen-docker_cli/blob/master/lib/kitchen/driver/docker_cli.rb#L102

Or , you can use the network stack of host by set `host` to `network` option.
`kitchen-docker` does not have this.
https://github.com/marcy-terui/kitchen-docker_cli/blob/master/README.md#network

**Comment by joerg** [comment]
Sorry for the late answer and thanks a lot. I think I confused your publish with dockers publish.
