### ISSUE TITLE
kitchen-ansible with extra_vars fail

### ISSUE THREAD

**Issue by yewton** [marcy-terui/kitchen-docker_cli#18]
I think kitchen-docker_cli itself is **NOT** responsible for this issue,
but adding a notice for the issue could be helpful.

If `extra_vars` specified, kitchen-ansible generates a JSON string(cf. https://github.com/neillturner/kitchen-ansible/blob/2f7aac93023e4e0602c854146c33ab4441c19408/lib/kitchen/provisioner/ansible_playbook.rb#L477-L478 ).
On the other hand, kitchen-docker_cli replaces all `'` in the command string to `"`.
So the result command looks like: `-e "{"a": "b"}"`
It causes an error :confounded:

I made a workaround ( https://github.com/yewton/kitchen-docker_cli/commit/c028a0a8fd03e8098986228746d7067b3285f1c8 ), but it seems test-kitchen's `wrap_command` should do that :confused: 
I'll more try on it.

Thank you!

**Comment by marcy-terui** [comment]
Thanks for reporting.

I think, escape will be better than the replacement.
So, I tried to implement the escape.

Because I do not know how to use the kitchen-ansible, could you try this branch?
https://github.com/marcy-terui/kitchen-docker_cli/tree/kitchen_ansible

**Comment by yewton** [comment]
It works! Thank you//// :laughing: 
I wrote a test to ensure that, see https://github.com/yewton/kitchen-docker_cli/commit/142de64d49c2edaec10ce0cf7bed0e751e1da934

**Comment by marcy-terui** [comment]
Good job :+1: Thanks :smile: 

I'll merge the branch and release it soon.

**Comment by marcy-terui** [comment]
Done. It is released in [v0.12.1](https://rubygems.org/gems/kitchen-docker_cli/versions/0.12.1)

Please check the new version :-)

**Comment by yewton** [comment]
Everything goes well.
Many thanks :+1:
