### ISSUE TITLE
No build context on remote docker hosts?

### ISSUE THREAD

**Issue by nrvale0** [marcy-terui/kitchen-docker_cli#22]
When testing with Docker Toolbox on OSX and a Dockerfile with a COPY, I get the following:

```ShellSession
...
Step 11 : COPY static /tmp/static
STDERR: static: no such file or directory
...
```

I suspect this might be because Docker Toolbox on OSX spawns a VirtualBox VM and the plugin is not copying the Docker build context to the "remote" Docker host. A manual build using 'docker build -f Dockerfile .' completes.

```ShellSession
$ docker build -f Dockerfile . ; echo $?
...
Successfully built 5cd7726ef1f8
0
```

The kitchen-docker plugin had a similar problem at one point:

https://github.com/portertech/kitchen-docker/commit/5d07ae0d2c472bb6377075519fa0a5521efbbe50

**Comment by marcy-terui** [comment]
@nrvale0 I think this problem has been fixed in #23 
Can I close this?

**Comment by nrvale0** [comment]
:+1:

Thanks!

**Comment by marcy-terui** [comment]
:+1: 
Thank you, too!
